services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_database
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: ghcr.io/skillplayground/kotlin-docker-google-cloud:latest
    container_name: app
    networks:
      - app-network
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=app_database

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
